"""initial migration

Revision ID: 988470676e5f
Revises: 
Create Date: 2025-07-28 20:49:41.615626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988470676e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
